#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Create symbolic links for configuration files
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc

# Update and install packages using apt
sudo apt update

packages=(
	fd-find
	ripgrep
	npm
	starship
	lazygit
)

for package in "${packages[@]}"; do
	echo "Installing $package..."
	sudo apt install -y "$package"
done

echo "All packages from the setup script have been installed."
