#!/bin/bash

# Define configuration home
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

# Create symbolic links for your Neovim and Zsh configuration
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.zshrc" "$HOME"/.zshrc

# Update the package manager and install essential dependencies
sudo apt update

# Essential packages needed for your Neovim setup
packages=(
	ripgrep  # For searching within files
	npm      # Node.js package manager, useful for Neovim plugins
	neovim   # Neovim itself
)

# Install each package
for package in "${packages[@]}"; do
	echo "Installing $package..."
	sudo apt install -y "$package"
done

# Install lazy.nvim if it's not already installed
if [ ! -d "$XDG_CONFIG_HOME/nvim/lazy/lazy.nvim" ]; then
    echo "Installing lazy.nvim..."
    git clone https://github.com/folke/lazy.nvim.git "$XDG_CONFIG_HOME/nvim/lazy/lazy.nvim"
fi

# Setting up Neovim plugins with lazy.nvim
echo "Setting up Neovim plugins..."
nvim --headless "+Lazy sync" +qa

echo "Dotfiles and environment have been set up successfully."
